apiVersion: batch/v1
kind: Job
metadata:
  name: workshop-setup
spec:
  template:
    spec:
      containers:
      - name: gitea-configurer
        image: ko://github.com/kameshsampath/drone-tutorial-gitea-helper/cmd/drone-tutorial-gitea-helper
        args:
          - "setup-workshop"
          - "--workshop-file=/config/workshop.yaml"
          - "--verbose=debug"
        volumeMounts:
          - mountPath: /config
            name: workshop-config
      restartPolicy: Never
      serviceAccountName: gitea-configurer
      volumes:
        - name: workshop-config
          configMap:
            name: workshop-config
  backoffLimit: 0


