# The Gitea Configuration
giteaAdminUserName: demo
giteaAdminUserPassword: demo@123
giteaURL: http://gitea-http.default:3000/
users:
  # the lower bound of user e.g. user-01
  from: 1
  # the upper bound of user e.g. user-10
  to: 3
  # create Gitea oAuth app for user
  oAuthAppName: demo-oauth
  # oAuth redirect URL
  oAuthRedirectURI: http://drone-127.0.0.1.sslip.io:30980
  # add oAuth App ClientID and ClientSecret to Kubernetes Secret
  addKubernetesSecret: true
  # The Namespace where to create the secret, the secret will 
  # use the format demo-oauth-<username>-secret
  secretNamespace: drone
  repos:
    - https://github.com/kameshsampath/jar-stack
