apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/version: "0.2.0"
  name: drone
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/version: "0.2.0"
  name: gitea-configurer
  namespace: drone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/version: "0.2.0"
  name: gitea-configurer
  namespace: drone
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/version: "0.2.0"
  name: gitea-configurer
  namespace: drone
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitea-configurer
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: gitea-configurer
    namespace: drone
---
apiVersion: v1
data:
  workshop.yaml: "# The Gitea Configuration\ngiteaAdminUserName: demo\ngiteaAdminUserPassword: demo@123\ngiteaURL: http://gitea-http.default:3000/\nusers:\n  # the lower bound of user e.g. user-01\n  from: 1\n  # the upper bound of user e.g. user-10\n  to: 3\n  # create Gitea oAuth app for user\n  oAuthAppName: demo-oauth\n  # oAuth redirect URL\n  oAuthRedirectURI: http://drone-127.0.0.1.sslip.io:30980\n  # add oAuth App ClientID and ClientSecret to Kubernetes Secret\n  addKubernetesSecret: true\n  # The Namespace where to create the secret, the secret will \n  # use the format demo-oauth-<username>-secret\n  secretNamespace: drone\n  repos:\n    - https://github.com/kameshsampath/jar-stack\n"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/version: "0.2.0"
  name: workshop-config
  namespace: drone
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/version: "0.2.0"
  name: workshop-setup
  namespace: drone
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/version: "0.2.0"
    spec:
      containers:
        - args:
            - setup-workshop
            - --workshop-file=/config/workshop.yaml
            - --verbose=debug
          image: docker.io/kameshsampath/drone-tutorial-gitea-helper:v0.2.0@sha256:2f9e10ed31a6cc8e1e24d6493028c63a325c029f9e63eb47d4bf75828c540dba
          name: gitea-configurer
          volumeMounts:
            - mountPath: /config
              name: workshop-config
      restartPolicy: Never
      serviceAccountName: gitea-configurer
      volumes:
        - configMap:
            name: workshop-config
          name: workshop-config

---
